[package]
name = "wiki-browser-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
wiki-common = { path = "../../shared/wiki-common" }
wiki-ui = { path = "../../ui/wiki-ui" }
wiki-ui-app = { path = "../../ui/wiki-ui-app" }
wasm-logger = "0.2"
gloo = { version = "0.11", features = ["storage"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
